/**
 * ============================================================================
 * AUTHENTICATION SERVICE — SUPABASE AUTH & PROFILES
 * APDAGU Enterprise v2.0
 * ============================================================================
 */

import { getSupabase } from './supabase.js';

class AuthService {
  constructor() {
    this.currentUser = null;
    this.currentProfile = null;
    this.authListeners = new Set();
  }

  async init() {
    const supabase = await getSupabase();
    if (!supabase) return null;

    // Listen for Supabase auth state change
    supabase.auth.onAuthStateChange(async (event, session) => {
      if (session?.user) {
        await this.loadProfile(session.user.id);
      } else {
        this.currentUser = null;
        this.currentProfile = null;
      }
      this.notifyListeners(event);
    });

    // Check existing session
    const { data: { session } } = await supabase.auth.getSession();
    if (session?.user) {
      this.currentUser = session.user;
      await this.loadProfile(session.user.id);
    }
    return this.currentUser;
  }

  async loadProfile(userId) {
    const supabase = await getSupabase();
    if (!supabase) return null;

    try {
      const { data, error } = await supabase
        .from('profiles')
        .select('*')
        .eq('id', userId)
        .single();

      if (error && error.code !== 'PGRST116') {
        console.warn('[AuthService] Profile fetch warning:', error.message);
      }

      if (data) {
        this.currentProfile = data;
      } else {
        // Fallback profile if row not yet generated by trigger
        this.currentProfile = {
          id: userId,
          role: 'guru',
          nama_lengkap: this.currentUser?.email?.split('@')[0] || 'Pengguna',
          email: this.currentUser?.email
        };
      }
      return this.currentProfile;
    } catch (e) {
      console.warn('[AuthService] Error loading profile:', e.message);
      return null;
    }
  }

  async login(email, password) {
    const supabase = await getSupabase();
    if (!supabase) throw new Error('Koneksi Supabase tidak tersedia.');

    // Support demo/shortcut login format if user enters plain username
    let loginEmail = email.trim();
    if (!loginEmail.includes('@')) {
      if (loginEmail === 'admin') loginEmail = 'admin@sdnsumberwaru2.sch.id';
      else if (loginEmail === 'operator') loginEmail = 'operator@sdnsumberwaru2.sch.id';
      else loginEmail = `${loginEmail}@sdnsumberwaru2.sch.id`;
    }

    const { data, error } = await supabase.auth.signInWithPassword({
      email: loginEmail,
      password: password
    });

    if (error) throw error;
    this.currentUser = data.user;
    await this.loadProfile(data.user.id);
    this.notifyListeners('SIGNED_IN');
    return { user: this.currentUser, profile: this.currentProfile };
  }

  async logout() {
    const supabase = await getSupabase();
    if (supabase) {
      await supabase.auth.signOut();
    }
    this.currentUser = null;
    this.currentProfile = null;
    localStorage.removeItem('apdagu_auth_token');
    this.notifyListeners('SIGNED_OUT');
  }

  async changePassword(newPassword) {
    const supabase = await getSupabase();
    if (!supabase) throw new Error('Koneksi Supabase tidak tersedia.');

    const { data, error } = await supabase.auth.updateUser({
      password: newPassword
    });
    if (error) throw error;
    return data;
  }

  getUser() {
    return this.currentUser;
  }

  getProfile() {
    return this.currentProfile || {
      role: 'guru',
      nama_lengkap: 'Tamu',
      email: ''
    };
  }

  getRole() {
    return this.currentProfile?.role || 'guru';
  }

  isAdmin() {
    return this.getRole() === 'admin';
  }

  isOperator() {
    return this.getRole() === 'operator';
  }

  isAdminOrOperator() {
    return ['admin', 'operator'].includes(this.getRole());
  }

  canEditGuru(guruId) {
    if (this.isAdminOrOperator()) return true;
    return this.currentProfile?.guru_id === guruId;
  }

  onAuthStateChange(callback) {
    this.authListeners.add(callback);
    return () => this.authListeners.delete(callback);
  }

  notifyListeners(event) {
    for (const callback of this.authListeners) {
      try {
        callback(event, { user: this.currentUser, profile: this.currentProfile });
      } catch (err) {
        console.error('[AuthService] Listener error:', err);
      }
    }
  }
}

export const Auth = new AuthService();
